import { Todo } from '../../types/Todo';

export interface TodoContextInterface {
  todos: Todo[],
  onTodos: React.Dispatch<React.SetStateAction<Todo[]>>,
  tempTodo: Todo | null,
  onTempTodo: (value: Todo | null) => void,
  query: string,
  onQuery: (value: string) => void,
  errorMessage: string,
  onErrorMessage: (value: string) => void,
  isTodoSelected: string,
  onIsTodoSelected: (value: string) => void,
  isTodoLoading: Todo | null,
  onIsTodoLoading: (value: Todo | null) => void,
  isAllTodosLoading: boolean,
  onIsAllTodosLoading: (value: boolean) => void,
  isInputDisabled: boolean,
  onIsInputDisabled: (value: boolean) => void,
  updatingForm: Todo | null,
  onUpdatingForm: (value: Todo | null) => void,
  updateInputFocus: boolean,
  onUpdateInputFocus: (value: boolean) => void,
  deleteTodos: (value: number) => {},
  completedTodos: Todo[],
  deleteCompletedTodos: (value: Todo[]) => {},
  updateTodos: (value: Todo) => Promise<void>,
  toggleAll: () => {},
  onCheckedToggle: (value: Todo) => {},
  copyOfTodos: Todo[],
}
